### ISSUE TITLE
Home Manager 2.0  Version 2.08.5.R  77_SMAEM.pm

### ISSUE THREAD

**Issue by fis1497** [kettenbach-it/FHEM-SMAEM#8]
Hi,
Mit der Version 2.07. war noch alles super mit dem Modul 77_SMAEM.pm
Dann kam in der Nacht das Update und es wurde sehr ruhig.
Auch im FHEM log ist nichts zu erkennen.
Gruß
Falk

**Comment by kettenbach-it** [comment]
Bitte im Forum fragen. Hier nur Support für Entwickler.

**Comment by ennosun** [comment]
Im Forum wurde darauf verwiesen hier einen Issue zu eröffnen. Ich schließe mich @fis1497 an, mit der Bitte um Integration in dein Modul der neuen SMA HM 2.0 Version 2.08.5.R. 

Was brauchst du noch für Informationen? Ich kann sonst sicher einen Multicast Auszug liefer, da ich ähnlich Schwierigkeiten mit der neuen Version habe. Die Daten werden nicht korrekt umgewandelt bzw. Die Listings entsprechen nicht mit dem Vergleich zum Portal

**Comment by kettenbach-it** [comment]
Das Produkt namens Homemanager2 kann ich nicht unterstützen.
Nur das Energy-Meter.
Ich rate, für Homemanager2 ein eigenes Modul zu entwickeln.
